<?xml version="1.0" encoding="UTF-8"?>
<!--
    $Author: gaobo.wang  
    $Date: 2013-1-29 下午2:43:19  
    $Revision: 1.0  
    $Purpose: 
-->
<bm:model xmlns:e="aurora.service.exception" xmlns:ns2="aurora.database.local.oracle" xmlns:bm="http://www.aurora-framework.org/schema/bm" xmlns:f="aurora.database.features" needAccessControl="false">
    <bm:operations>
        <bm:operation name="update">
            <bm:update-sql><![CDATA[
    			begin
    				eam_asset_entity_classes_pkg.update_entity_unit(p_class_id                  => ${@class_id},
									                               p_entity_man_company_id      => ${@entity_man_company_id},
									                               p_entity_man_unit_id         => ${@entity_man_unit_id},
									                               p_entity_man_position_id     => ${@entity_man_position_id},
									                               p_responsibility_employee_id => ${@responsibility_employee_id},
									                               p_user_id                    => ${/session/@user_id});
    			end;
    		]]></bm:update-sql>
        </bm:operation>
    </bm:operations>
</bm:model>
